create table competencias
(
    id               int auto_increment
        primary key,
    tipo_competencia varchar(16) not null,
    codigo           varchar(16) not null,
    descripcion      text        null
);

INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (1, 'Basica', 'CB1', 'Que los estudiantes hayan demostrado poseer y comprender conocimientos en un área de estudio que parte de la base de la educación secundaria general, y se suele encontrar a un nivel que, si bien se apoya en libros de texto avanzados, incluye también algunos aspectos que implican conocimientos procedentes de la vanguardia de su campo de estudio.');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (2, 'Basica', 'CB2', 'Que los estudiantes sepan aplicar sus conocimientos a su trabajo o vocación de una forma profesional y posean las competencias que suelen demostrarse mediante la elaboración y defensa de argumentos y la resolución de problemas dentro de su área de estudio');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (3, 'Basica', 'CB3', 'Que los estudiantes tengan la capacidad de reunir e interpretar datos relevantes (normalmente dentro de su área de estudio) para emitir juicios que incluyan una reflexión sobre temas relevantes de índole social, científica o ética');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (4, 'Basica', 'CB4', 'Que los estudiantes puedan transmitir información, ideas, problemas y soluciones a un público tanto especializado como no especializado');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (5, 'Basica', 'CB5', 'Que los estudiantes hayan desarrollado aquellas habilidades de aprendizaje necesarias para emprender estudios posteriores con un alto grado de autonomía');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (6, 'General', 'CG10', 'Conocimientos para la realización de mediciones, cálculos, valoraciones, tasaciones, peritaciones, estudios, informes, planificación de tareas y otros trabajos análogos de informática, de acuerdo con los conocimientos adquiridos según lo establecido en el apartado 5, anexo 2, de la resolución BOE-A');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (7, 'General', 'CG11', 'Capacidad para analizar y valorar el impacto social y medioambiental de las soluciones técnicas, comprendiendo la responsabilidad ética y profesional de la actividad del Ingeniero Técnico en Informática');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (8, 'General', 'CG3', 'Capacidad para diseñar, desarrollar, evaluar y asegurar la accesibilidad, ergonomía, usabilidad y seguridad de los sistemas, servicios y aplicaciones informáticas, así como de la información que gestionan');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (9, 'General', 'CG4', 'Capacidad para definir, evaluar y seleccionar plataformas hardware y software para el desarrollo y la ejecución de sistemas, servicios y aplicaciones informáticas, de acuerdo con los conocimientos adquiridos según lo establecido en el apartado 5, anexo 2, de la resolución BOE-A');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (10, 'General', 'CG5', 'Capacidad para concebir, desarrollar y mantener sistemas, servicios y aplicaciones informáticas empleando los métodos de la ingeniería del software como instrumento para el aseguramiento de su calidad, de acuerdo con los conocimientos adquiridos según lo establecido en el apartado 5, anexo 2, de la resolución BOE-A');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (11, 'General', 'CG6', 'Capacidad para concebir y desarrollar sistemas o arquitecturas informáticas centralizadas o distribuidas integrando hardware, software y redes de acuerdo con los conocimientos adquiridos según lo establecido en el apartado 5, anexo 2, de la resolución BOE-A');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (12, 'General', 'CG8', 'Conocimiento de las materias básicas y tecnologías, que capaciten para el aprendizaje y desarrollo de nuevos métodos y tecnologías, así como las que les doten de una gran versatilidad para adaptarse a nuevas situaciones');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (13, 'General', 'CG9', 'Capacidad para resolver problemas con iniciativa, toma de decisiones, autonomía y creatividad. Capacidad para saber comunicar y transmitir los conocimientos, habilidades y destrezas de la profesión de Ingeniero Técnico en Informática');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (14, 'Interna', 'CIB4', 'Conocimientos básicos sobre el uso y programación de los ordenadores, sistemas operativos, bases de datos y programas informáticos con aplicación en ingeniería');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (15, 'Interna', 'CIB5', 'Conocimiento de la estructura, organización, funcionamiento e interconexión de los sistemas informáticos, los fundamentos de su programación, y su aplicación para la resolución de problemas propios de la ingeniería.');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (16, 'Interna', 'CIC6', 'Capacidad para comprender, aplicar y gestionar la garantía y seguridad de los sistemas informáticos');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (17, 'Interna', 'CSI2', 'Capacidad para determinar los requisitos de los sistemas de información y comunicación de una organización atendiendo a aspectos de seguridad y cumplimiento de la normativa y la legislación vigente');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (18, 'Interna', 'CSI5', 'Capacidad para comprender y aplicar los principios de la evaluación de riesgos y aplicarlos correctamente en la elaboración y ejecución de planes de actuación');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (19, 'Resultado Aprend', 'RA1', 'Conocer los fundamentos de un sistema operativo, sus componentes y los conceptos esenciales para la comprensión de los mismos');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (20, 'Resultado Aprend', 'RA2', 'Conocer diversos sistemas operativos y entornos de operación (tradicionales, GUI, multimedia, etc.), sus diferencias y requisitos en términos de recursos');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (21, 'Resultado Aprend', 'RA3', 'Conocer el problema de la integración de sistemas y determinar los requisitos de interoperabilidad');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (22, 'Resultado Aprend', 'RA4', 'Instalar, configurar y operar un sistema operativo multiusuario');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (23, 'Resultado Aprend', 'RA5', 'Razonar la necesidad de los sistemas operativos en los entornos de computación actuales');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (24, 'Resultado Aprend', 'RA6', 'Explicar el papel del sistema operativo como interfaz entre el hardware y los programas de usuario');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (25, 'Resultado Aprend', 'RA7', 'Diferenciar las más relevantes técnicas de planificación de tareas, tanto para sistemas batch, interactivos y de tiempo real');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (26, 'Resultado Aprend', 'RA8', 'Comprender las técnicas generales de gestión de E/S y su relación con el sistema de archivos. Cada resultado del aprendizaje puede aparecer asociado a varias partes de la asignatura, tratándose en cada una de ellas según una óptica práctica, teórica o analítica, siendo el conjunto de las partes el que define el resultado final. Por ello, para superar la asignatura es necesario que no existan vacíos en ninguna de las formas de enfocar los resultados de aprendizaje');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (27, 'Transversal', 'TRU1', 'Capacidad de análisis y síntesis');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (28, 'Transversal', 'TRU2', 'Comunicación oral y escrita');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (29, 'Transversal', 'TRU3', 'Capacidad de gestión de la información');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (30, 'Transversal', 'TRU4', 'Capacidad de aprendizaje autónomo');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (31, 'Transversal', 'TRU5', 'Capacidad para trabajar en equipo');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (32, 'Prueba', 'P1', 'Colaborar con los demás para el bien común');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (33, 'Prueba', 'P2', 'Aplicar las reglas del cálculo diferencial para resolver problemas');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (34, 'Prueba', 'P3', 'Aplicar las reglas del cálculo integral para calcular áreas y volúmenes');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (35, 'Prueba', 'P4', 'Utilizar las matrices para resolver sistemas de ecuaciones');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (36, 'Prueba', 'P5', 'Aplicar las leyes de la física para explicar el comportamiento de la materia');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (37, 'Prueba', 'P6', 'Comprender los procesos psicológicos');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (38, 'Prueba', 'P7', 'Comprender y utilizar un idioma extranjero');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (39, 'Prueba', 'P8', 'Leer y escribir textos en un idioma extranjero');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (40, 'Prueba', 'P9', 'Utilizar un traductor para traducir entre idiomas');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (41, 'Prueba', 'P10', 'Generar ideas creativas para resolver problemas');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (42, 'Prueba', 'P11', 'Evaluar el trabajo de otros de forma objetiva');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (43, 'Prueba', 'P12', 'Tomar decisiones de forma efectiva');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (44, 'Prueba', 'P13', 'Cumplir con sus obligaciones y responsabilidades');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (45, 'Prueba', 'P14', 'Actuar con integridad y honestidad');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (46, 'Prueba', 'P15', 'Colaborar con los demás para alcanzar un objetivo común');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (47, 'Prueba', 'P16', 'Desarrollar aplicaciones móviles en Java');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (48, 'Prueba', 'P17', 'Diseñar y desarrollar videojuegos');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (49, 'Prueba', 'P18', 'otra competencia de prueba para el form post');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (50, 'Prueba', 'P19', 'otra competencia de prueba para el form post');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (51, 'Prueba', 'P20', 'otra competencia de prueba para el form post');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (52, 'Prueba', 'P21', 'GúenIMechuIndeSameer');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (53, 'Prueba', 'P22', 'sdasdasd');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (54, 'string', 'string', 'string');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (55, 'Resultado A', 'RA23', 'Describir la evolución de los lenguajes de programación, los diferentes paradigmas disponibles hoy día y sus principales características');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (56, 'Resultado A', 'RA33', 'Expresar el concepto de tipo de dato y tipo abstracto de dato y ser capaz de identificar las características principales de un sistema de tipos');
INSERT INTO erappsmus.competencias (id, tipo_competencia, codigo, descripcion) VALUES (57, 'General', 'CG234', 'wfdsafsfadsfs');
