create table paises
(
    id     int auto_increment
        primary key,
    codigo varchar(2)  not null,
    region varchar(16) null,
    nombre varchar(64) not null
);

INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (7, 'AF', null, 'Afganistán');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (8, 'AX', null, 'Islas Aland');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (9, 'AL', null, 'Albania');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (10, 'DZ', null, 'Argelia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (11, 'AS', null, 'Samoa Americana');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (12, 'AD', null, 'Andorra');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (13, 'AO', null, 'Angola');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (14, 'AI', null, 'Anguila');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (15, 'AQ', null, 'Antártida');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (16, 'AG', null, 'Antigua y Barbuda');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (17, 'AR', null, 'Argentina');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (18, 'AM', null, 'Armenia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (19, 'AW', null, 'Aruba');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (20, 'AU', null, 'Australia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (21, 'AT', null, 'Austria');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (22, 'AZ', null, 'Azerbaiyán');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (23, 'BS', null, 'Bahamas');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (24, 'BH', null, 'Bahrain');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (25, 'BD', null, 'Bangladesh');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (26, 'BB', null, 'Barbados');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (27, 'BY', null, 'Bielorrusia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (28, 'BE', null, 'Bélgica');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (29, 'BZ', null, 'Belgo');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (30, 'BJ', null, 'Benin');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (31, 'BM', null, 'islas Bermudas');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (32, 'BT', null, 'Bután');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (33, 'BO', null, 'Bolivia, estado plurinacional de');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (34, 'BQ', null, 'Bonaire, Sint Eustatius y Saba');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (35, 'BA', null, 'Bosnia y Herzegovina');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (36, 'BW', null, 'Botswana');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (37, 'BV', null, 'Isla bouvet');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (38, 'BR', null, 'Brasil');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (39, 'IO', null, 'Territorio Británico del Océano Índico');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (40, 'BN', null, 'Brunei Darussalam');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (41, 'BG', null, 'Bulgaria');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (42, 'BF', null, 'Burkina Faso');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (43, 'BI', null, 'Burundi');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (44, 'KH', null, 'Camboya');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (45, 'CM', null, 'Camerún');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (46, 'CA', null, 'Canada');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (47, 'CV', null, 'Capa verde');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (48, 'KY', null, 'Islas Caimán');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (49, 'CF', null, 'República Centroafricana');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (50, 'TD', null, 'Chad');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (51, 'CL', null, 'Chile');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (52, 'CN', null, 'Porcelana');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (53, 'CX', null, 'Isla de Navidad');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (54, 'CC', null, 'Islas Cocos (Keeling)');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (55, 'CO', null, 'Colombia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (56, 'KM', null, 'Comoras');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (57, 'CG', null, 'Congo');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (58, 'CD', null, 'Congo, la República Democrática del');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (59, 'CK', null, 'Islas Cook');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (60, 'CR', null, 'Costa Rica');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (61, 'CI', null, 'Costa de Marfil');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (62, 'HR', null, 'Croacia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (63, 'CU', null, 'Cuba');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (64, 'CW', null, 'Curaçao');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (65, 'CY', null, 'Chipre');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (66, 'CZ', null, 'República Checa');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (67, 'DK', null, 'Dinamarca');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (68, 'DJ', null, 'Djibouti');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (69, 'DM', null, 'Dominio');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (70, 'DO', null, 'República Dominicana');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (71, 'EC', null, 'Ecuador');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (72, 'EG', null, 'Egipto');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (73, 'SV', null, 'El Salvador');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (74, 'GQ', null, 'Guinea Ecuatorial');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (75, 'ER', null, 'Eritrea');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (76, 'EE', null, 'Estonia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (77, 'ET', null, 'Etiopía');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (78, 'FK', null, 'Islas Malvinas (Malvinas)');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (79, 'FO', null, 'Islas Faroe');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (80, 'FJ', null, 'Fiji');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (81, 'FI', null, 'Finlandia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (82, 'FR', null, 'Francia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (83, 'GF', null, 'Guayana Francesa');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (84, 'PF', null, 'Polinesia francés');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (85, 'TF', null, 'Territorios Franceses del Sur');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (86, 'GA', null, 'Gabón');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (87, 'GM', null, 'Gambia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (88, 'GE', null, 'Georgia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (89, 'DE', null, 'Alemania');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (90, 'GH', null, 'Ghana');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (91, 'GI', null, 'Gibraltar');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (92, 'GR', null, 'Grecia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (93, 'GL', null, 'Groenlandia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (94, 'GD', null, 'Granada');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (95, 'GP', null, 'Guadeloupo');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (96, 'GU', null, 'Guam');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (97, 'GT', null, 'Guatemala');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (98, 'GG', null, 'Guía');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (99, 'GN', null, 'Guinea');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (100, 'GW', null, 'Guinea-Bissau');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (101, 'GY', null, 'Guayana');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (102, 'HT', null, 'Haití');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (103, 'HM', null, 'Escuché Island y Islas McDonald');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (104, 'VA', null, 'Santa Sede (Estado de la Ciudad del Vaticano)');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (105, 'HN', null, 'Honduras');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (106, 'HK', null, 'Hong Kong');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (107, 'HU', null, 'Hungría');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (108, 'IS', null, 'Islandia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (109, 'IN', null, 'India');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (110, 'ID', null, 'Indonesia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (111, 'IR', null, 'Irán (República Islámica de');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (112, 'IQ', null, 'Irak');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (113, 'IE', null, 'Irlanda');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (114, 'IM', null, 'Isla del hombre');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (115, 'IL', null, 'Israel');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (116, 'IT', null, 'Italia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (117, 'JM', null, 'Jamaica');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (118, 'JP', null, 'Japón');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (119, 'JE', null, 'Jersey');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (120, 'JO', null, 'Jordán');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (121, 'KZ', null, 'Kazajstán');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (122, 'KE', null, 'Kenia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (123, 'KI', null, 'Kiribati');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (124, 'KP', null, 'República de Corea, Popular Democrática de');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (125, 'KR', null, 'Corea, república de');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (126, 'KW', null, 'Kuwait');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (127, 'KG', null, 'Kirguistán');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (128, 'LA', null, 'República Democrática Popular de Lao');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (129, 'LV', null, 'Letonia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (130, 'LB', null, 'Líbano');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (131, 'LS', null, 'Lesoto');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (132, 'LR', null, 'Liberia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (133, 'LY', null, 'Libia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (134, 'LI', null, 'Liechtenstein');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (135, 'LT', null, 'Lituania');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (136, 'LU', null, 'Luxemburgo');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (137, 'MO', null, 'Macao');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (138, 'MK', null, 'Macedonia, la antigua república yugoslava de');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (139, 'MG', null, 'Madagascar');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (140, 'MW', null, 'Fuego');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (141, 'MY', null, 'Malasia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (142, 'MV', null, 'Maldivas');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (143, 'ML', null, 'Tuve que');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (144, 'MT', null, 'Malta');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (145, 'MH', null, 'Islas Marshall');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (146, 'MQ', null, 'Martinica');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (147, 'MR', null, 'Mauritania');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (148, 'MU', null, 'Mauricio');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (149, 'YT', null, 'Mayotte');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (150, 'MX', null, 'México');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (151, 'FM', null, 'Micronesia, estados federados de');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (152, 'MD', null, 'Moldavia, República de');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (153, 'MC', null, 'Mónaco');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (154, 'MN', null, 'Mongolia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (155, 'ME', null, 'Montenegro');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (156, 'MS', null, 'Montserrat');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (157, 'MA', null, 'Marruecos');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (158, 'MZ', null, 'Mozambique');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (159, 'MM', null, 'Myanmar');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (160, 'NA', null, 'Namibia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (161, 'NR', null, 'Nauru');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (162, 'NP', null, 'Nepal');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (163, 'NL', null, 'Países Bajos');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (164, 'NC', null, 'Nueva Caledonia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (165, 'NZ', null, 'Nueva Zelanda');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (166, 'NI', null, 'Nicaragua');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (167, 'NE', null, 'Níger');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (168, 'NG', null, 'Nigeria');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (169, 'NU', null, 'Niue');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (170, 'NF', null, 'Isla Norfolk');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (171, 'MP', null, 'Islas Marianas del Norte');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (172, 'NO', null, 'Noruega');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (173, 'OM', null, 'Uno mismo');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (174, 'PK', null, 'Pakistán');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (175, 'PW', null, 'Palau');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (176, 'PS', null, 'Palestina, estado de');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (177, 'PA', null, 'Panamá');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (178, 'PG', null, 'Papúa Nueva Guinea');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (179, 'PY', null, 'Paraguay');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (180, 'PE', null, 'Perú');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (181, 'PH', null, 'Filipinas');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (182, 'PN', null, 'Pitcairn');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (183, 'PL', null, 'Polonia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (184, 'PT', null, 'Portugal');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (185, 'PR', null, 'Puerto Rico');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (186, 'QA', null, 'Katar');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (187, 'RE', null, 'Reunión');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (188, 'RO', null, 'Rumania');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (189, 'RU', null, 'Federación Rusa');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (190, 'RW', null, 'Ruanda');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (191, 'BL', null, 'Santa Barthélemy');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (192, 'SH', null, 'Santa Helena, Ascensión y Tristan da Cunha');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (193, 'KN', null, 'Saint Kitts y Nevis');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (194, 'LC', null, 'Saint Lucia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (195, 'MF', null, 'San Martín (parte francesa)');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (196, 'PM', null, 'Saint Pierre y Miquelon');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (197, 'VC', null, 'San Vicente y las Granadinas');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (198, 'WS', null, 'Samoa');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (199, 'SM', null, 'San Marino');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (200, 'ST', null, 'Santo Tomé y Príncipe');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (201, 'SA', null, 'Arabia Saudita');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (202, 'SN', null, 'Senegal');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (203, 'RS', null, 'Serbia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (204, 'SC', null, 'Seychelles');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (205, 'SL', null, 'Sierra Leona');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (206, 'SG', null, 'Singapur');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (207, 'SX', null, 'Sint Marthes (parte holandesa)');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (208, 'SK', null, 'Eslovaquia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (209, 'SI', null, 'Eslovenia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (210, 'SB', null, 'Islas Salomón');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (211, 'SO', null, 'Somalia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (212, 'ZA', null, 'Sudáfrica');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (213, 'GS', null, 'Georgia del sur y las islas Sandwich del sur');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (214, 'SS', null, 'Sudán del Sur');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (215, 'ES', null, 'España');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (216, 'LK', null, 'Sri Lanka');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (217, 'SD', null, 'Sudán');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (218, 'SR', null, 'Surinam');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (219, 'SJ', null, 'Svalbard y Jan Mayen');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (220, 'SZ', null, 'Swazilandia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (221, 'SE', null, 'Suecia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (222, 'CH', null, 'Suiza');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (223, 'SY', null, 'República Árabe Siria');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (224, 'TW', null, 'Taiwan, provincia de China');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (225, 'TJ', null, 'Tayikistán');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (226, 'TZ', null, 'Tanzania, República Unida de');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (227, 'TH', null, 'Tailandia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (228, 'TL', null, 'Leer Timor');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (229, 'TG', null, 'Ir');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (230, 'TK', null, 'Tokelau');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (231, 'TO', null, 'Llegó');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (232, 'TT', null, 'Trinidad y Tobago');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (233, 'TN', null, 'Túnez');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (234, 'TR', null, 'Turquía');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (235, 'TM', null, 'Turkmenistán');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (236, 'TC', null, 'Islas Turcas y Caicos');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (237, 'TV', null, 'Tuvalu');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (238, 'UG', null, 'Uganda');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (239, 'UA', null, 'Ucrania');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (240, 'AE', null, 'Emiratos Árabes Unidos');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (241, 'GB', null, 'Reino Unido');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (242, 'US', null, 'Estados Unidos');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (243, 'UM', null, 'Islas menores de los Estados Unidos.');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (244, 'UY', null, 'Uruguay');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (245, 'UZ', null, 'Uzbekistán');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (246, 'VU', null, 'Vanuatu');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (247, 'VE', null, 'Venezuela, República Bolíva de');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (248, 'VN', null, 'Vietnam');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (249, 'VG', null, 'Islas Vírgenes, Británica');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (250, 'VI', null, 'Islas Vírgenes, EE. UU.');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (251, 'WF', null, 'Wallis y Futuna');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (252, 'EH', null, 'Sahara Occidental');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (253, 'YE', null, 'Yemen');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (254, 'ZM', null, 'Zambia');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (255, 'ZW', null, 'Zimbabue');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (256, 'PR', 'Mi mundo', 'Prieba');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (257, 'PR', 'Mi mundo', 'Prieba');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (258, 'LL', 'adasd', 'Prieba3');
INSERT INTO erappsmus.paises (id, codigo, region, nombre) VALUES (259, 'KL', '', 'EDEFTGG');
