create table universidades
(
    id           int auto_increment
        primary key,
    codigo       varchar(255) not null,
    pais         int          not null,
    nombre       varchar(255) not null,
    hace_erasmus tinyint(1)   not null,
    ciudad       varchar(255) null,
    constraint universidades_pk2
        unique (codigo),
    constraint universidades_paises_id_fk
        foreign key (pais) references paises (id)
);

INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (1, 'UAH', 215, 'Universidad De Alcalá', 1, 'Madrid');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (6, 'D  AACHEN02', 89, 'FACHHOCHSCHULE AACHEN', 1, 'AACHEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (7, 'D  AACHEN01', 89, 'RHEINISCH-WESTFAELISCHE TECHNISCHE HOCHSCHULE AACHEN', 1, 'AACHEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (8, 'D  AALEN01', 89, 'HOCHSCHULE AALEN - TECHNIK UND WIRTSCHAFT', 1, 'AALEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (9, 'D  AUGSBUR02', 89, 'Hochschule für angewandte Wissenschaften Augsburg', 1, 'Augsburg');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (10, 'D  AUGSBUR01', 89, 'UNIVERSITAET AUGSBURG', 1, 'AUGSBURG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (11, 'D  BAMBERG01', 89, 'OTTO-FRIEDRICH-UNIVERSITAET BAMBERG', 1, 'BAMBERG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (12, 'D  BERLIN01', 89, 'FREIE UNIVERSITAET BERLIN', 1, 'BERLIN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (13, 'D  BERLIN13', 89, 'HUMBOLDT-UNIVERSITAET ZU BERLIN', 1, 'BERLIN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (14, 'D  BIELEFE01', 89, 'UNIVERSITAET BIELEFELD', 1, 'BIELEFELD');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (15, 'D  BOCHUM02', 89, 'HOCHSCHULE BOCHUM', 1, 'BOCHUM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (16, 'D  BOCHUM01', 89, 'RUHR-UNIVERSITAET BOCHUM', 1, 'BOCHUM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (17, 'D  BREMEN01', 89, 'UNIVERSITAET BREMEN', 1, 'BREMEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (18, 'D  CHEMNIT01', 89, 'TECHNISCHE UNIVERSITAET CHEMNITZ', 1, 'CHEMNITZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (19, 'D  CLAUSTH01', 89, 'TECHNISCHE UNIVERSITAT CLAUSTHAL', 1, 'CLAUSTHAL ZELLERFELD');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (20, 'D  COTTBUS03', 89, 'BRANDENBURGISCHE TECHNISCHE UNIVERSITAT COTTBUS-SENFTENBERG', 1, 'COTTBUS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (21, 'D  DARMSTA01', 89, 'TECHNISCHE UNIVERSITAT DARMSTADT', 1, 'DARMSTADT');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (22, 'D  DEGGEND01', 89, 'TECHNISCHE HOCHSCHULE DEGGENDORF', 1, 'DEGGENDORF');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (23, 'D  DRESDEN02', 89, 'TECHNISCHE UNIVERSITAET DRESDEN', 1, 'DRESDEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (24, 'D  DUSSELD01', 89, 'HEINRICH-HEINE-UNIVERSITAET DUESSELDORF', 1, 'DUSSELDORF');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (25, 'D  EICHSTA01', 89, 'KATHOLISCHE UNIVERSITAT EICHSTATT-INGOLSTADT', 1, 'Eichstätt');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (26, 'D  ERFURT05', 89, 'UNIVERSITAT ERFURT', 1, 'ERFURT');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (27, 'D  ERLANGE01', 89, 'FRIEDRICH-ALEXANDER-UNIVERSITAET ERLANGEN NUERNBERG', 1, 'ERLANGEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (28, 'D  FRANKFU01', 89, 'JOHANN WOLFGANG GOETHE-UNIVERSITATFRANKFURT AM MAIN', 1, 'FRANKFURT AM MAIN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (29, 'D  FREIBUR01', 89, 'ALBERT-LUDWIGS-UNIVERSITAET FREIBURG', 1, 'FREIBURG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (30, 'D  GIESSEN02', 89, 'TECHNISCHE HOCHSCHULE MITTELHESSEN', 1, 'GIESSEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (31, 'D  GOTTING01', 89, 'GEORG-AUGUST-UNIVERSITAT GOTTINGENSTIFTUNG OFFENTLICHEN RECHTS', 1, 'GOTTINGEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (32, 'D  HAMBURG06', 89, 'HOCHSCHULE FUR ANGEWANDTE WISSENSCHAFTEN HAMBURG', 1, 'HAMBURG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (33, 'D  HAMBURG03', 89, 'TECHNISCHE UNIVERSITAT HAMBURG', 1, 'HAMBURG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (34, 'D  HAMBURG01', 89, 'UNIVERSITAET HAMBURG', 1, 'HAMBURG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (35, 'D  HANNOVE01', 89, 'GOTTFRIED WILHELM LEIBNIZ UNIVERSITAET HANNOVER', 1, 'HANNOVER');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (36, 'D  HANNOVE02', 89, 'MEDIZINISCHE HOCHSCHULE HANNOVER', 1, 'HANNOVER');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (37, 'D  HEIDELB05', 89, 'SRH HOCHSCHULE HEIDELBERG GMBH', 1, 'HEIDELBERG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (38, 'D  INGOLST01', 89, 'TECHNISCHE HOCHSCHULE INGOLSTADT', 1, 'INGOLSTADT');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (39, 'D  JENA01', 89, 'FRIEDRICH-SCHILLER-UNIVERSITAT JENA', 1, 'JENA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (40, 'D  KAISERS02', 89, 'HOCHSCHULE KAISERSLAUTERN', 1, 'KAISERSLAUTERN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (41, 'D  KARLSRU07', 89, 'Duale Hochschule Baden-Württemberg Karlsruhe', 1, 'Karlsruhe');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (42, 'D  KEMPTEN01', 89, 'HOCHSCHULE FUR ANGEWANDTE WISSENSCHAFTEN KEMPTEN', 1, 'KEMPTEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (43, 'D  KEMPTEN02', 89, 'Institut fuer Fremdsprachen-Berufe GmbH - Fachakademie fuer Uebersetzen und Dolmetschen', 1, 'Kempten');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (44, 'D  KIEL01', 89, 'CHRISTIAN-ALBRECHTS-UNIVERSITAET  ZU KIEL', 1, 'KIEL');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (45, 'D  KOLN07', 89, 'RFH-Koeln gGmbh', 1, 'Koeln');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (46, 'D  KOLN01', 89, 'UNIVERSITAET ZU KOELN', 1, 'KOELN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (47, 'D  KOLN04', 89, 'TECHNISCHE HOCHSCHULE KOLN', 1, 'KOLN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (48, 'D  KONSTAN02', 89, 'HOCHSCHULE KONSTANZ TECHNIK WIRTSCHAFT UND GESTALTUNG', 1, 'KONSTANZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (49, 'D  KONSTAN01', 89, 'UNIVERSITAT KONSTANZ', 1, 'KONSTANZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (50, 'D  LANDSHU01', 89, 'HOCHSCHULE FUR ANGEWANDTE WISSENSCHAFTEN FACHHOCHSCHULE LANDSHUT', 1, 'LANDSHUT');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (51, 'D  LEIPZIG01', 89, 'UNIVERSITAET LEIPZIG', 1, 'LEIPZIG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (52, 'D  MAGDEBU01', 89, 'OTTO-VON-GUERICKE-UNIVERSITAET MAGDEBURG', 1, 'MAGDEBURG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (53, 'D  MAINZ08', 89, 'HOCHSCHULE MAINZ UNIVERSITY OF APPLIED SCIENCES', 1, 'MAINZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (54, 'D  MAINZ01', 89, 'JOHANNES GUTENBERG-UNIVERSITAT MAINZ', 1, 'MAINZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (55, 'D  MANNHEI08', 89, 'Duale Hochschule Baden-Württemberg Mannheim', 1, 'Mannheim');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (56, 'D  MANNHEI01', 89, 'UNIVERSITAET MANNHEIM', 1, 'MANNHEIM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (57, 'D  MARBURG01', 89, 'PHILIPPS UNIVERSITAET MARBURG', 1, 'MARBURG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (58, 'D  MITTWEI01', 89, 'HOCHSCHULE MITTWEIDA (FH)', 1, 'MITTWEIDA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (59, 'D  MOSBACH01', 89, 'Duale Hochschule Baden-Württemberg Mosbach', 1, 'Mosbach');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (60, 'D  MUNCHEN02', 89, 'TECHNISCHE UNIVERSITAET MUENCHEN', 1, 'MUENCHEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (61, 'D  MUNSTER01', 89, 'WESTFAELISCHE WILHELMS-UNIVERSITAET MUENSTER', 1, 'MUENSTER');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (62, 'D  MUNCHEN11', 89, 'SPRACHEN- UND DOLMETSCHER-INSTITUTMUNCHEN EV', 1, 'MUNCHEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (63, 'D  MUNCHEN10', 89, 'UNIVERSITAET DER BUNDESWEHR MUENCHEN', 1, 'NEUBIBERG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (64, 'D  OSNABRU01', 89, 'UNIVERSITAET OSNABRUECK', 1, 'OSNABRUECK');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (65, 'D  PADERBO01', 89, 'UNIVERSITAET PADERBORN', 1, 'PADERBORN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (66, 'D  PASSAU01', 89, 'UNIVERSITAT PASSAU', 1, 'PASSAU');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (67, 'D  PFORZHE01', 89, 'HOCHSCHULE PFORZHEIM', 1, 'PFORZHEIM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (68, 'D  REGENSB01', 89, 'UNIVERSITAET REGENSBURG', 1, 'REGENSBURG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (69, 'D  ROSTOCK01', 89, 'UNIVERSITAET ROSTOCK', 1, 'ROSTOCK');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (70, 'D  SAARBRU01', 89, 'UNIVERSITAT DES SAARLANDES', 1, 'SAARBRUCKEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (71, 'D  SCHMALK01', 89, 'HOCHSCHULE SCHMALKALDEN', 1, 'SCHMALKALDEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (72, 'D  SIEGEN01', 89, 'UNIVERSITAET SIEGEN', 1, 'SIEGEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (73, 'D  STUTTGA02', 89, 'UNIVERSITAET HOHENHEIM', 1, 'STUTTGART');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (74, 'D  STUTTGA01', 89, 'UNIVERSITAET STUTTGART', 1, 'STUTTGART');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (75, 'D  TRIER01', 89, 'UNIVERSITAT TRIER', 1, 'TRIER');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (76, 'D  TUBINGE01', 89, 'EBERHARD KARLS UNIVERSITAET TUEBINGEN', 1, 'TUEBINGEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (77, 'D  ULM01', 89, 'UNIVERSITAET ULM', 1, 'ULM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (78, 'D  VILLING02', 89, 'Duale Hochschule Baden-Württemberg Villingen-Schwenningen', 1, 'Villingen-Schwenningen');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (79, 'D  WURZBUR03', 89, 'University of Applied Sciences Wuerzburg-Schweinfurt', 1, 'Wuerzburg');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (80, 'D  WUPPERT01', 89, 'BERGISCHE UNIVERSITAET  WUPPERTAL', 1, 'WUPPERTAL');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (81, 'D  ZWICKAU01', 89, 'WESTSACHSISCHE HOCHSCHULE ZWICKAU', 1, 'ZWICKAU');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (82, 'A  GRAZ09', 21, 'FH JOANNEUM GESELLSCHAFT MBH', 1, 'GRAZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (83, 'A  GRAZ02', 21, 'TECHNISCHE UNIVERSITAET GRAZ', 1, 'GRAZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (84, 'A  GRAZ01', 21, 'UNIVERSITAET GRAZ', 1, 'GRAZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (85, 'A  INNSBRU01', 21, 'UNIVERSITAET INNSBRUCK', 1, 'INNSBRUCK');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (86, 'A  KLAGENF02', 21, 'Pädagogische Hochschule Kärnten', 1, 'Klagenfurt');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (87, 'A  KREMS03', 21, 'IMC FACHHOCHSCHULE KREMS GMBH', 1, 'KREMS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (88, 'A  LINZ01', 21, 'UNIVERSITAT LINZ', 1, 'LINZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (89, 'A  SALZBUR01', 21, 'PARIS-LODRON-UNIVERSITAT SALZBURG', 1, 'SALZBURG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (90, 'A  WELS01', 21, 'FH OO STUDIENBETRIEBS GMBH', 1, 'WELS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (91, 'A  WIEN15', 21, 'HOCHSCHULE FUR AGRAR- UND UMWELTPADAGOGIK', 1, 'Wien');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (92, 'A  WIEN01', 21, 'UNIVERSITAT WIEN', 1, 'WIEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (93, 'B  ANTWERP01', 28, 'UNIVERSITEIT ANTWERPEN', 1, 'ANTWERPEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (94, 'B  BRUSSEL46', 28, 'ERASMUSHOGESCHOOL BRUSSEL', 1, 'BRUSSEL');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (95, 'B  BRUSSEL01', 28, 'VRIJE UNIVERSITEIT BRUSSEL', 1, 'BRUSSEL');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (96, 'B  BRUXEL86', 28, 'GROUPE ICHEC - ISC SAINT-LOUIS - ISFSC', 1, 'BRUXELLES');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (97, 'B  BRUXEL02', 28, 'UNIVERSITE SAINT-LOUIS-BRUXELLES ASBL', 1, 'BRUXELLES');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (98, 'B  GENT01', 28, 'UNIVERSITEIT GENT', 1, 'GENT');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (99, 'B  LEUVEN01', 28, 'KATHOLIEKE UNIVERSITEIT LEUVEN', 1, 'LEUVEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (100, 'B  LIEGE01', 28, 'UNIVERSITE DE LIEGE', 1, 'LIEGE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (101, 'B  LOUVAIN01', 28, 'UNIVERSITE CATHOLIQUE DE LOUVAIN', 1, 'LOUVAIN LA NEUVE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (102, 'BG SOFIA17', 41, 'NATSIONALNA SPORTNA AKADEMIYA VASSIL LEVSKI', 1, 'SOFIA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (103, 'BG SOFIA02', 41, 'NEW bgN UNIVERSITY', 1, 'SOFIA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (104, 'BG SOFIA16', 41, 'TECHNICAL UNIVERSITY OF SOFIA', 1, 'SOFIA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (105, 'BG SOFIA04', 41, 'UNIVERSITET PO ARCHITEKTURA STROITELSTVO I GEODEZIJA', 1, 'SOFIA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (106, 'CY NICOSIA01', 65, 'UNIVERSITY OF CYPRUS', 1, 'NICOSIA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (107, 'CY NICOSIA14', 65, 'University of Nicosia', 1, 'Nicosia');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (108, 'HR PULA01', 62, 'SVEUCILISTE JURJA DOBRILE U PULI', 1, 'PULA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (109, 'HR RIJEKA01', 62, 'SVEUCILISTE U RIJECI', 1, 'RIJEKA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (110, 'HR ZADAR01', 62, 'SVEUCILISTE U ZADRU', 1, 'ZADAR');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (111, 'HR ZAGREB01', 62, 'SVEUCILISTE U ZAGREBU', 1, 'ZAGREB');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (112, 'DK ALBORG01', 67, 'AALBORG UNIVERSITET', 1, 'AALBORG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (113, 'DK ARHUS01', 67, 'AARHUS UNIVERSITET', 1, 'AARHUS C');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (114, 'DK ODENSE01', 67, 'SYDDANSK UNIVERSITET', 1, 'ODENSE M');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (115, 'SK BRATISL03', 208, 'EKONOMICKA UNIVERZITA V BRATISLAVE', 1, 'BRATISLAVA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (116, 'SK BRATISL01', 208, 'SLOVENSKA TECHNICKA UNIVERZITA V BRATISLAVE', 1, 'BRATISLAVA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (117, 'SK KOSICE01', 208, 'UNIVERZITA VETERINARSKEHO LEKARSTVA A FARMACIE V KOSICIACH', 1, 'Kosice');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (118, 'SK PRESOV01', 208, 'PRESOVSKA UNIVERZITA V PRESOVE', 1, 'PRESOV');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (119, 'SK TRNAVA01', 208, 'TRNAVSKA UNIVERZITA V TRNAVE', 1, 'TRNAVA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (120, 'SI LJUBLJA01', 209, 'UNIVERZA V LJUBLJANI', 1, 'LJUBLJANA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (121, 'SI MARIBOR01', 209, 'UNIVERZA V MARIBORU', 1, 'MARIBOR');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (122, 'EE TALLINN04', 76, 'TALLINNA TEHNIKAULIKOOL', 1, 'TALLINN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (123, 'EE TARTU01', 76, 'EESTI MAAULIKOOL', 1, 'TARTU');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (124, 'EE TARTU02', 76, 'TARTU ULIKOOL', 1, 'TARTU');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (125, 'SF HELSINK41', 81, 'METROPOLIA AMMATTIKORKEAKOULU OY', 1, 'HELSINKI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (126, 'SF JYVASKY11', 81, 'JYVASKYLAN AMMATTIKORKEAKOULU', 1, 'JYVASKYLA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (127, 'SF KUOPIO12', 81, 'ITA-SUOMEN YLIOPISTO', 1, 'KUOPIO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (128, 'SF ROVANIE01', 81, 'LAPIN YLIOPISTO', 1, 'ROVANIEMI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (129, 'SF SEINAJO06', 81, 'SEINAJOEN AMMATTIKORKEAKOULU OY', 1, 'SEINAJOKI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (130, 'SF TAMPERE17', 81, 'TAMPEREEN KORKEAKOULUSAATIO SR', 1, 'TAMPERE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (131, 'SF VANTAA06', 81, 'LAUREA-AMMATTIKORKEAKOULU OY', 1, 'VANTAA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (132, 'F  AMIENS27', 82, 'Association Groupe Sup de Co Amiens Picardie', 1, 'AMIENS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (133, 'F  AMIENS01', 82, 'UNIVERSITE DE PICARDIE JULES VERNE', 1, 'AMIENS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (134, 'F  ANGERS01', 82, 'UNIVERSITE D\'ANGERS', 1, 'ANGERS CEDEX 01');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (135, 'F  ANGERS08', 82, 'ASS GROUPE ECOLE SUPERIEURE AGRICULTURE', 1, 'ANGERS CEDEX 1');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (136, 'F  ARRAS12', 82, 'UNIVERSITE D\'ARTOIS', 1, 'ARRAS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (137, 'F  BORDEAU58', 82, 'UNIVERSITE DE BORDEAUX', 1, 'BORDEAUX');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (138, 'F  BREST27', 82, 'Institut Régional de Formation Sanitaire et Sociale Croix-Rouge française Bretagne', 1, 'BREST');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (139, 'F  CERGY07', 82, 'université de Cergy-Pontoise', 1, 'CERGY-PONTOISE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (140, 'F  CLERMON46', 82, 'Groupe ESC Clermont - Auvergne', 1, 'Clermont-Ferrand');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (141, 'F  CLERMON48', 82, 'UNIVERSITE CLERMONT AUVERGNE', 1, 'CLERMONT-FERRAND');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (142, 'F  DIJON01', 82, 'UNIVERSITE DIJON BOURGOGNE', 1, 'DIJON CEDEX');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (143, 'F  DUNKERQ09', 82, 'UNIVERSITE DU LITTORAL', 1, 'Dunkerque');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (144, 'F  EVRY04', 82, 'UNIVERSITE D\'EVRY-VAL D\'ESSONE', 1, 'EVRY');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (145, 'F  LA-ROCH07', 82, 'Excelia Group', 1, 'LA ROCHELLE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (146, 'F  LA-ROCH08', 82, 'UNIVERSITE DE LA ROCHELLE', 1, 'LA ROCHELLE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (147, 'F  LE-HAVR04', 82, 'ECOLE DE MANAGEMENT DE NORMANDIE', 1, 'LE HAVRE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (148, 'F  LILLE103', 82, 'UNIVERSITE DE LILLE', 1, 'LILLE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (149, 'F  LIMOGES20', 82, 'Groupe 3iL', 1, 'LIMOGES');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (150, 'F  LYON71', 82, 'CENTRE D\'ETUDES EUROPEEN RHONE ALPES- C.E.E. RHONE ALPES', 1, 'LYON');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (151, 'F  LYON02', 82, 'UNIVERSITE LUMIERE LYON 2', 1, 'LYON');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (152, 'F  LYON03', 82, 'UNIVERSITE LYON 3 JEAN MOULIN', 1, 'LYON CEDEX 08');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (153, 'F  LYON104', 82, 'INSTITUT D ENSEIGNEMENT SUPERIEUR ET DE RECHERCHE EN ALIMENTATION SANTE ANIMALE SCIENCES AGRONOMIQUES ETDE L ENVIRONNEMENT VETAGRO SUP', 1, 'MARCY L ETOILE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (154, 'F  MARSEIL51', 82, 'ECOLE SUPERIEURE D\'ART ET DE DESIGN MARSEILLE MEDITERRANEE', 1, 'Marseille');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (155, 'F  MARSEIL84', 82, 'UNIVERSITE D\'AIX MARSEILLE', 1, 'Marseille');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (156, 'F  ROUEN01', 82, 'UNIVERSITE DE ROUEN NORMANDIE', 1, 'MONT SAINT AIGNAN CEDEX');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (157, 'F  MONTPEL13', 82, 'GROUPE SUP DE CO MONTPELLIER', 1, 'MONTPELLIER');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (158, 'F  NANCY43', 82, 'UNIVERSITE DE LORRAINE', 1, 'NANCY CEDEX');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (159, 'F  PARIS010', 82, 'UNIVERSITE PARIS NANTERRE', 1, 'NANTERRE CEDEX');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (160, 'F  NANTES13', 82, 'ECOLE NATIONALE SUPERIEURE D\'ARCHITECTURE DE NANTES', 1, 'NANTES CEDEX 2');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (161, 'F  NICE41', 82, 'COMMUNAUTE D\'UNIVERSITES ET ETABLISSEMENTS UNIVERSITE COTE D\'AZUR', 1, 'NICE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (162, 'F  NICE01', 82, 'UNIVERSITE DE NICE SOPHIA ANTIPOLIS', 1, 'NICE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (163, 'F  ORLEANS01', 82, 'UNIVERSITE D\'ORLEANS', 1, 'ORLEANS CEDEX 2');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (164, 'F  PARIS011', 82, 'UNIVERSITE PARIS-SUD', 1, 'ORSAY CEDEX');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (165, 'F  PARIS190', 82, 'Ecole nationale supérieure d\'architecture de Paris-Belleville', 1, 'Paris');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (166, 'F  PARIS121', 82, 'ECOLE SPECIALE D\'ARCHITECTURE', 1, 'PARIS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (167, 'F  PARIS213', 82, 'Ecole Supérieure du Commerce Extérieur', 1, 'PARIS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (168, 'F  PARIS379', 82, 'INSTITUT DE MANAGEMENT ET DE COMMUNICATION INTERCULTURELS ASSOCIATION', 1, 'PARIS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (169, 'F  PARIS244', 82, 'INSTITUT DES HAUTES ETUDES ECONOMIQUES ET COMMERCIALES', 1, 'PARIS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (170, 'F  PARIS468', 82, 'SORBONNE UNIVERSITE', 1, 'PARIS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (171, 'F  PARIS008', 82, 'UNIVERSITE PARIS 8 VINCENNES SAINT-DENIS', 1, 'PARIS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (172, 'F  PARIS003', 82, 'UNIVERSITE PARIS III SORBONNE NOUVELLE', 1, 'PARIS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (173, 'F  PARIS002', 82, 'UNIVERSITE PARIS II PANTHEON ASSAS', 1, 'PARIS 05');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (174, 'F  PARIS009', 82, 'UNIVERSITE PARIS DAUPHINE', 1, 'PARIS CEDEX 16');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (175, 'F  PAU01', 82, 'UNIVERSITE DE PAU ET DES PAYS DE L\'ADOUR', 1, 'PAU');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (176, 'F  PERPIGN01', 82, 'UNIVERSITE DE PERPIGNAN', 1, 'PERPIGNAN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (177, 'F  BORDEAU03', 82, 'UNIVERSITE BORDEAUX MONTAIGNE', 1, 'PESSAC');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (178, 'F  BORDEAU41', 82, 'Université Montesquieu-Bordeaux IV', 1, 'Pessac');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (179, 'F  POINT-P05', 82, 'UNIVERSITE DES ANTILLES', 1, 'POINTE A PITRE CEDEX');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (180, 'F  POITIER01', 82, 'UNIVERSITE DE POITIERS', 1, 'POITIERS CEDEX');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (181, 'F  RENNES02', 82, 'UNIVERSITE RENNES II', 1, 'RENNES CEDEX');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (182, 'F  ST-DENI01', 82, 'UNIVERSITE DE LA REUNION', 1, 'SAINT DENIS DE LA REUNION CEDEX 9');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (183, 'F  ROUEN06', 82, 'INSTITUT NATIONAL DES SCIENCES APPLIQUEES DE ROUEN', 1, 'SAINT ETIENNE DU ROUVRAY');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (184, 'F  GRENOBL46', 82, 'COMMUNAUTE D\'UNIVERSITES ET ETABLISSEMENTS UNIVERSITE GRENOBLE ALPES', 1, 'SAINT MARTIN D HERES');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (185, 'F  GRENOBL51', 82, 'UNIVERSITE GRENOBLE ALPES', 1, 'SAINT MARTIN D\'HERES');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (186, 'F  STRASBO48', 82, 'UNIVERSITE DE STRASBOURG', 1, 'STRASBOURG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (187, 'F  BORDEAU16', 82, 'Ecole nationale supérieure d\'architecture et de paysage de Bordeaux', 1, 'Talence');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (188, 'F  TOULOUS02', 82, 'UNIVERSITE DE TOULOUSE II - LE MIRAIL', 1, 'TOULOUSE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (189, 'F  TOULOUS03', 82, 'UNIVERSITE PAUL SABATIER TOULOUSE III', 1, 'TOULOUSE CEDEX 9');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (190, 'F  TOURS01', 82, 'UNIVERSITE DE TOURS', 1, 'TOURS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (191, 'F  LILLE91', 82, 'IMT LILLE DOUAI', 1, 'VILLENEUVE D\'ASCQ CEDEX');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (192, 'F  PARIS013', 82, 'UNIVERSITE PARIS 13', 1, 'VILLETANEUSE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (193, 'F  LYON01', 82, 'UNIVERSITE LYON 1 CLAUDE BERNARD', 1, 'VILLEURBANNE CEDEX');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (194, 'G  ATHINE04', 92, 'ATHENS UNIVERSITY OF ECONOMICS AND BUSINESS - RESEARCH CENTER', 1, 'ATHENS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (195, 'G  ATHINE01', 92, 'ETHNIKO KAI KAPODISTRIAKO PANEPISTIMIO ATHINON', 1, 'ATHINA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (196, 'G  KAVALA01', 92, 'TECHNOLOGIKO EKPEDEFTIKO IDRIMA ANATOLIKIS MAKEDONIAS & THRAKIS', 1, 'KAVALA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (197, 'G  PATRA01', 92, 'PANEPISTIMIO PATRON', 1, 'RIO PATRAS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (198, 'G  THESSAL01', 92, 'ARISTOTELIO PANEPISTIMIO THESSALONIKIS', 1, 'THESSALONIKI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (199, 'G  VOLOS01', 92, 'PANEPISTIMIO THESSALIAS', 1, 'VOLOS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (200, 'HU BUDAPES20', 107, 'BUDAPESTI GAZDASAGI EGYETEM', 1, 'BUDAPEST');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (201, 'HU BUDAPES02', 107, 'BUDAPESTI MUSZAKI ES GAZDASAGTUDOMANYI EGYETEM', 1, 'BUDAPEST');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (202, 'HU DEBRECE01', 107, 'DEBRECENI EGYETEM', 1, 'DEBRECEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (203, 'IRLCORK01', 113, 'UNIVERSITY COLLEGE CORK -  NATIONAL UNIVERSITY OF IRELAND, CORK', 1, 'CORK');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (204, 'IRLDUBLIN04', 113, 'DUBLIN CITY UNIVERSITY', 1, 'DUBLIN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (205, 'IRLDUBLIN44', 113, 'TECHNOLOGICAL UNIVERSITY DUBLIN', 1, 'DUBLIN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (206, 'IRLDUBLIN01', 113, 'THE PROVOST, FELLOWS, FOUNDATION SCHOLARS & THE OTHER MEMBERS OF BOARD OF THE COLLEGE OF THE HOLY & UNDIVIDED TRINITY OF QUEEN ELIZABETH NEAR DUBLIN', 1, 'DUBLIN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (207, 'IRLGALWAY01', 113, 'NATIONAL UNIVERSITY OF IRELAND GALWAY', 1, 'GALWAY');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (208, 'IRLLETTERK01', 113, 'LETTERKENNY INSTITUTE OF TECHNOLOGY', 1, 'LETTERKENNY');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (209, 'IRLLIMERIC01', 113, 'UNIVERSITY OF LIMERICK', 1, 'LIMERICK');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (210, 'IRLMAYNOOT01', 113, 'NATIONAL UNIVERSITY OF IRELAND MAYNOOTH', 1, 'MAYNOOTH');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (211, 'I  COSENZA01', 116, 'UNIVERSITA DELLA CALABRIA', 1, 'ARCAVACATA DI RENDE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (212, 'I  BARI05', 116, 'POLITECNICO DI BARI', 1, 'BARI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (213, 'I  BARI01', 116, 'UNIVERSITA DEGLI STUDI DI BARI ALDO MORO', 1, 'BARI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (214, 'I  BENEVEN02', 116, 'UNIVERSITA DEGLI STUDI DEL SANNIO', 1, 'BENEVENTO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (215, 'I  BERGAMO01', 116, 'UNIVERSITA\' DEGLI STUDI DI BERGAMO', 1, 'BERGAMO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (216, 'I  BOLOGNA01', 116, 'ALMA MATER STUDIORUM - UNIVERSITA DI BOLOGNA', 1, 'BOLOGNA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (217, 'I  BRESCIA01', 116, 'UNIVERSITA DEGLI STUDI DI BRESCIA', 1, 'BRESCIA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (218, 'I  CAGLIAR01', 116, 'UNIVERSITA DEGLI STUDI DI CAGLIARI', 1, 'CAGLIARI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (219, 'I  NAPOLI09', 116, 'UNIVERSITA DEGLI STUDI DELLA CAMPANIA LUIGI VANVITELLI', 1, 'CASERTA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (220, 'I  CHIETI01', 116, 'UNIVERSITA DEGLI STUDI GABRIELE D\'ANNUNZIO DI CHIETI-PESCARA', 1, 'CHIETI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (221, 'I  FERRARA01', 116, 'UNIVERSITA DEGLI STUDI DI FERRARA', 1, 'FERRARA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (222, 'I  FIESOLE01', 116, 'EUROPEAN UNIVERSITY INSTITUTE', 1, 'FIESOLE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (223, 'I  SALERNO01', 116, 'UNIVERSITA DEGLI STUDI DI SALERNO', 1, 'FISCIANO SA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (224, 'I  FIRENZE01', 116, 'UNIVERSITA DEGLI STUDI DI FIRENZE', 1, 'Florence');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (225, 'I  FOGGIA03', 116, 'UNIVERSITA DEGLI STUDI DI FOGGIA', 1, 'FOGGIA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (226, 'I  GENOVA01', 116, 'UNIVERSITA DEGLI STUDI DI GENOVA', 1, 'GENOVA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (227, 'I  L-AQUIL01', 116, 'UNIVERSITA DEGLI STUDI DELL\'AQUILA', 1, 'L AQUILA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (228, 'I  LECCE01', 116, 'UNIVERSITA DEL SALENTO', 1, 'LECCE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (229, 'I  MACERAT01', 116, 'UNIVERSITA DEGLI STUDI DI MACERATA', 1, 'MACERATA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (230, 'I  MESSINA01', 116, 'UNIVERSITA DEGLI STUDI DI MESSINA', 1, 'MESSINA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (231, 'I  MILANO02', 116, 'POLITECNICO DI MILANO', 1, 'MILANO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (232, 'I  MILANO03', 116, 'UNIVERSITA CATTOLICA DEL SACRO CUORE', 1, 'MILANO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (233, 'I  MILANO01', 116, 'UNIVERSITA DEGLI STUDI DI MILANO', 1, 'MILANO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (234, 'I  MODENA01', 116, 'UNIVERSITA DEGLI STUDI DI MODENA E REGGIO EMILIA', 1, 'MODENA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (235, 'I  NAPOLI01', 116, 'UNIVERSITA DEGLI STUDI DI NAPOLI FEDERICO II', 1, 'NAPOLI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (236, 'I  NAPOLI03', 116, 'UNIVERSITA DEGLI STUDI DI NAPOLI PARTHENOPE', 1, 'NAPOLI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (237, 'I  NAPOLI04', 116, 'UNIVERSITA DEGLI STUDI SUOR ORSOLA BENINCASA', 1, 'NAPOLI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (238, 'I  PADOVA01', 116, 'UNIVERSITA DEGLI STUDI DI PADOVA', 1, 'PADOVA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (239, 'I  PALERMO01', 116, 'UNIVERSITA DEGLI STUDI DI PALERMO', 1, 'PALERMO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (240, 'I  PARMA01', 116, 'UNIVERSITA DEGLI STUDI DI PARMA', 1, 'PARMA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (241, 'I  PAVIA01', 116, 'UNIVERSITA DEGLI STUDI DI PAVIA', 1, 'PAVIA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (242, 'I  PERUGIA01', 116, 'UNIVERSITA DEGLI STUDI DI PERUGIA', 1, 'PERUGIA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (243, 'I  PISA01', 116, 'UNIVERSITA DI PISA', 1, 'PISA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (244, 'I  ROMA04', 116, 'LIBERA UNIVERSITA MARIA SS. ASSUNTA DI ROMA', 1, 'ROMA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (245, 'I  ROMA05', 116, 'UNIVERSITA DEGLI STUDI DI ROMA FORO ITALICO', 1, 'ROMA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (246, 'I  ROMA01', 116, 'UNIVERSITA DEGLI STUDI DI ROMA LA SAPIENZA', 1, 'ROMA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (247, 'I  ROMA02', 116, 'UNIVERSITA DEGLI STUDI DI ROMA TOR VERGATA', 1, 'ROMA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (248, 'I  ROMA16', 116, 'UNIVERSITA DEGLI STUDI ROMA TRE', 1, 'ROMA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (249, 'I  SALERNO02', 116, 'Conservatorio di Musica Giuseppe Martucci Salerno', 1, 'Salerno');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (250, 'I  SASSARI01', 116, 'UNIVERSITA DEGLI STUDI DI SASSARI', 1, 'SASSARI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (251, 'I  SIENA01', 116, 'UNIVERSITA DEGLI STUDI DI SIENA', 1, 'SIENA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (252, 'I  TORINO01', 116, 'UNIVERSITA DEGLI STUDI DI TORINO', 1, 'TORINO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (253, 'I  TRENTO01', 116, 'UNIVERSITA DEGLI STUDI DI TRENTO', 1, 'TRENTO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (254, 'I  TRIESTE01', 116, 'UNIVERSITA DEGLI STUDI DI TRIESTE', 1, 'TRIESTE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (255, 'I  UDINE01', 116, 'UNIVERSITA DEGLI STUDI DI UDINE', 1, 'UDINE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (256, 'I  URBINO01', 116, 'Universita\' degli Studi di Urbino Carlo Bo', 1, 'URBINO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (257, 'I  VARESE02', 116, 'UNIVERSITA DEGLI STUDI DELL\'INSUBRIA', 1, 'VARESE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (258, 'I  VENEZIA01', 116, 'UNIVERSITA CA\' FOSCARI VENEZIA', 1, 'VENEZIA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (259, 'I  VENEZIA02', 116, 'UNIVERSITA IUAV DI VENEZIA', 1, 'VENEZIA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (260, 'I  VERCELL01', 116, 'UNIVERSITA DEGLI STUDI DEL PIEMONTE ORIENTALE AMEDEO AVOGADRO', 1, 'VERCELLI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (261, 'I  VERONA01', 116, 'UNIVERSITA DEGLI STUDI DI VERONA', 1, 'VERONA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (262, 'I  VITERBO01', 116, 'UNIVERSITA DEGLI STUDI DELLA TUSCIA', 1, 'VITERBO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (263, 'LV RIGA08', 129, 'LATVIJAS KULTURAS AKADEMIJA', 1, 'Riga');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (264, 'LV RIGA01', 129, 'LATVIJAS UNIVERSITATE', 1, 'RIGA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (265, 'LV RIGA09', 129, 'SIA BIZNESA AUGSTSKOLA TURIBA', 1, 'RIGA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (266, 'LT KAUNAS01', 135, 'VYTAUTO DIDZIOJO UNIVERSITETAS', 1, 'KAUNAS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (267, 'LT KLAIPED04', 135, 'VIESOJI ISTAIGA SOCIALINIU MOKSLU KOLEGIJA', 1, 'KLAIPEDA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (268, 'LT VILNIUS20', 135, 'VIESOJI ISTAIGA EUROPOS HUMANITARINIS UNIVERSITETAS', 1, 'VILNIUS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (269, 'LT VILNIUS02', 135, 'VILNIAUS GEDIMINO TECHNIKOS UNIVERSITETAS', 1, 'VILNIUS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (270, 'LT VILNIUS01', 135, 'VILNIAUS UNIVERSITETAS', 1, 'VILNIUS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (271, 'LUXLUX-VIL01', 136, 'UNIVERSITE DU LUXEMBOURG', 1, 'ESCH-SUR-ALZETTE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (272, 'MT MALTA01', 144, 'UNIVERSITA TA MALTA', 1, 'MSIDA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (273, 'N  BERGEN14', 172, 'HOGSKULEN PA VESTLANDET', 1, 'BERGEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (274, 'N  BERGEN01', 172, 'UNIVERSITETET I BERGEN', 1, 'BERGEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (275, 'N  ELVERUM02', 172, 'HOGSKOLEN I INNLANDET', 1, 'ELVERUM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (276, 'N  OSLO01', 172, 'UNIVERSITETET I OSLO', 1, 'OSLO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (277, 'N  KONGSBE02', 172, 'UNIVERSITETET I SOROST-NORGE', 1, 'PORSGRUNN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (278, 'N  VOLDA01', 172, 'Høgskulen i Volda', 1, 'Volda');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (279, 'NL AMSTERD01', 163, 'UNIVERSITEIT VAN AMSTERDAM', 1, 'AMSTERDAM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (280, 'NL S-GRAVE37', 163, 'STICHTING HOGER ONDERWIJS NEDERLAND', 1, 'DEN HAAG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (281, 'NL GRONING03', 163, 'HANZEHOGESCHOOL GRONINGEN STICHTING', 1, 'GRONINGEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (282, 'NL GRONING01', 163, 'RIJKSUNIVERSITEIT GRONINGEN', 1, 'GRONINGEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (283, 'NL LEIDEN01', 163, 'UNIVERSITEIT LEIDEN', 1, 'LEIDEN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (284, 'NL ROTTERD01', 163, 'ERASMUS UNIVERSITEIT ROTTERDAM', 1, 'ROTTERDAM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (285, 'NL UTRECHT24', 163, 'Stichting Hogeschool Utrecht', 1, 'UTRECHT');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (286, 'NL UTRECHT01', 163, 'UNIVERSITEIT UTRECHT', 1, 'UTRECHT');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (287, 'PL GDANSK06', 183, 'AKADEMIA WYCHOWANIA FIZYCZNEGO I SPORTU IM JEDRZEJA SNIADECKIEGO W GDANSKU OLIWIE', 1, 'GDANSK');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (288, 'PL GDANSK03', 183, 'GDANSKI UNIWERSYTET MEDYCZNY', 1, 'GDANSK');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (289, 'PL GDANSK02', 183, 'POLITECHNIKA GDANSKA', 1, 'GDANSK');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (290, 'PL GDANSK01', 183, 'UNIWERSYTET GDANSKI', 1, 'GDANSK');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (291, 'PL GDANSK10', 183, 'Wyzsza Szkola Zdrowia w Gdansku', 1, 'Gdańsk');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (292, 'PL GLIWICE01', 183, 'POLITECHNIKA SLASKA', 1, 'GLIWICE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (293, 'PL KATOWIC01', 183, 'UNIWERSYTET SLASKI', 1, 'KATOWICE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (294, 'PL KRAKOW03', 183, 'POLITECHNIKA KRAKOWSKA', 1, 'KRAKOW');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (295, 'PL KRAKOW04', 183, 'UNIWERSYTET EKONOMICZNY W KRAKOWIE', 1, 'KRAKOW');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (296, 'PL KRAKOW01', 183, 'UNIWERSYTET JAGIELLONSKI', 1, 'KRAKOW');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (297, 'PL KRAKOW05', 183, 'UNIWERSYTET PEDAGOGICZNY IM KOMISJI EDUKACJI NARODOWEJ W KRAKOWIE', 1, 'KRAKOW');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (298, 'PL LODZ02', 183, 'POLITECHNIKA LODZKA', 1, 'LODZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (299, 'PL LODZ09', 183, 'SPOLECZNA AKADEMIA NAUK', 1, 'LODZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (300, 'PL LODZ01', 183, 'UNIWERSYTET LODZKI', 1, 'LODZ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (301, 'PL NOWY-TA01', 183, 'Podhalanska Panstwowa Uczelnia Zawodowa w Nowym Targu', 1, 'Nowy Targ');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (302, 'PL OLSZTYN01', 183, 'UNIWERSYTET WARMINSKO MAZURSKI W OLSZTYNIE', 1, 'OLSZTYN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (303, 'PL OPOLE01', 183, 'UNIWERSYTET OPOLSKI', 1, 'OPOLE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (304, 'PL POZNAN01', 183, 'UNIWERSYTET IM. ADAMA MICKIEWICZA W POZNANIU', 1, 'POZNAN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (305, 'PL SZCZECI01', 183, 'UNIWERSYTET SZCZECINSKI', 1, 'SZCZECIN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (306, 'PL TORUN01', 183, 'UNIWERSYTET MIKOLAJA KOPERNIKA W TORUNIU', 1, 'TORUN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (307, 'PL WARSZAW12', 183, 'AKADEMIA WYCHOWANIA FIZYCZNEGO JOZEFA PILSUDSKIEGO W WARSZAWIE', 1, 'WARSZAWA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (308, 'PL WARSZAW02', 183, 'POLITECHNIKA WARSZAWSKA', 1, 'WARSZAWA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (309, 'PL WARSZAW01', 183, 'UNIWERSYTET WARSZAWSKI', 1, 'WARSZAWA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (310, 'PL WARSZAW06', 183, 'WARSZAWSKI UNIWERSYTET MEDYCZNY', 1, 'WARSZAWA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (311, 'PL WROCLAW01', 183, 'UNIWERSYTET WROCLAWSKI', 1, 'WROCLAW');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (312, 'PL ZIELONA01', 183, 'UNIWERSYTET ZIELONOGORSKI', 1, 'ZIELONA GORA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (313, 'P  AVEIRO01', 184, 'UNIVERSIDADE DE AVEIRO', 1, 'AVEIRO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (314, 'P  BRAGA01', 184, 'UNIVERSIDADE DO MINHO', 1, 'BRAGA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (315, 'P  CASTELO01', 184, 'INSTITUTO POLITECNICO DE CASTELO BRANCO', 1, 'CASTELO BRANCO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (316, 'P  COIMBRA24', 184, 'ESCOLA SUPERIOR DE ENFERMAGEM DE COIMBRA', 1, 'COIMBRA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (317, 'P  COIMBRA01', 184, 'UNIVERSIDADE DE COIMBRA', 1, 'COIMBRA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (318, 'P  COVILHA01', 184, 'UNIVERSIDADE DA BEIRA INTERIOR', 1, 'COVILHA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (319, 'P  FUNCHAL03', 184, 'Universidade da Madeira', 1, 'Funchal');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (320, 'P  LISBOA11', 184, 'C.E.U - COOPERATIVA DE ENSINO UNIVERSITARIO CRL', 1, 'LISBOA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (321, 'P  LISBOA107', 184, 'Escola Superior de Enfermagem S. Francisco das Misericórdias', 1, 'Lisboa');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (322, 'P  LISBOA05', 184, 'INSTITUTO POLITECNICO DE LISBOA', 1, 'LISBOA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (323, 'P  LISBOA01', 184, 'UNIVERSIDADE CATOLICA PORTUGUESA', 1, 'LISBOA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (324, 'P  LISBOA109', 184, 'UNIVERSIDADE DE LISBOA', 1, 'LISBOA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (325, 'P  LISBOA03', 184, 'UNIVERSIDADE NOVA DE LISBOA', 1, 'LISBOA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (326, 'P  ACORES01', 184, 'UNIVERSIDADE DOS ACORES', 1, 'PONTA DELGADA S MIGUEL ACORES');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (327, 'P  PORTO02', 184, 'UNIVERSIDADE DO PORTO', 1, 'PORTO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (328, 'P  PORTO57', 184, 'Universidade Lusófona do Porto -- COFAC', 1, 'Porto');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (329, 'P  SETUBAL01', 184, 'INSTITUTO POLITECNICO DE SETUBAL', 1, 'SETUBAL');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (330, 'P  VILA-RE01', 184, 'UNIVERSIDADE DE TRAS-OS-MONTES E ALTO DOURO', 1, 'VILA REAL');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (331, 'UK BELFAST01', 241, 'THE QUEEN\'S UNIVERSITY OF BELFAST', 1, 'BELFAST');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (332, 'UK BIRMING03', 241, 'BIRMINGHAM CITY UNIVERSITY', 1, 'BIRMINGHAM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (333, 'UK BIRMING02', 241, 'THE UNIVERSITY OF BIRMINGHAM', 1, 'BIRMINGHAM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (334, 'UK BRIGHTO02', 241, 'UNIVERSITY OF BRIGHTON', 1, 'BRIGHTON');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (335, 'UK CAMBRID01', 241, 'THE CHANCELLOR MASTERS AND SCHOLARS OF THE UNIVERSITY OF CAMBRIDGE', 1, 'CAMBRIDGE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (336, 'UK COVENTR02', 241, 'COVENTRY UNIVERSITY', 1, 'COVENTRY');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (337, 'UK DURHAM01', 241, 'UNIVERSITY OF DURHAM', 1, 'DURHAM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (338, 'UK EDINBUR01', 241, 'THE UNIVERSITY OF EDINBURGH', 1, 'EDINBURGH');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (339, 'UK LONDON097', 241, 'ROYAL HOLLOWAY AND BEDFORD NEW COLLEGE', 1, 'EGHAM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (340, 'UK EXETER01', 241, 'THE UNIVERSITY OF EXETER', 1, 'EXETER');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (341, 'UK GLASGOW01', 241, 'UNIVERSITY OF GLASGOW', 1, 'GLASGOW');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (342, 'UK HATFIEL01', 241, 'THE UNIVERSITY OF HERTFORDSHIRE HIGHER EDUCATION CORPORATION', 1, 'HATFIELD');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (343, 'UK KEELE01', 241, 'UNIVERSITY OF KEELE', 1, 'KEELE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (344, 'UK LEEDS01', 241, 'UNIVERSITY OF LEEDS', 1, 'LEEDS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (345, 'UK LEICEST01', 241, 'UNIVERSITY OF LEICESTER', 1, 'LEICESTER');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (346, 'UK LIVERPO01', 241, 'THE UNIVERSITY OF LIVERPOOL', 1, 'LIVERPOOL');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (347, 'UK LONDON031', 241, 'QUEEN MARY UNIVERSITY OF LONDON', 1, 'LONDON');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (348, 'UK MANCHES04', 241, 'THE MANCHESTER METROPOLITAN UNIVERSITY', 1, 'MANCHESTER');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (349, 'UK MANCHES01', 241, 'THE UNIVERSITY OF MANCHESTER', 1, 'MANCHESTER');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (350, 'UK NORWICH01', 241, 'UNIVERSITY OF EAST ANGLIA', 1, 'NORWICH');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (351, 'UK NOTTING02', 241, 'THE NOTTINGHAM TRENT UNIVERSITY', 1, 'NOTTINGHAM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (352, 'UK OXFORD04', 241, 'OXFORD BROOKES UNIVERSITY', 1, 'OXFORD');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (353, 'UK PORTSMO01', 241, 'UNIVERSITY OF PORTSMOUTH HIGHER EDUCATION CORPORATION', 1, 'PORTSMOUTH');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (354, 'UK READING01', 241, 'THE UNIVERSITY OF READING', 1, 'READING');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (355, 'UK SOUTHAM01', 241, 'UNIVERSITY OF SOUTHAMPTON', 1, 'SOUTHAMPTON');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (356, 'UK ST-ANDR01', 241, 'THE UNIVERSITY COURT OF THE UNIVERSITY OF ST ANDREWS', 1, 'ST ANDREWS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (357, 'UK SWANSEA01', 241, 'SWANSEA UNIVERSITY', 1, 'SWANSEA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (358, 'UK DEESIDE01', 241, 'GLYNDWR UNIVERSITY/PRIFYSGOL GLYNDWR', 1, 'WREXHAM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (359, 'CZ BRNO06', 66, 'VETERINARNI A FARMACEUTICKA UNIVERZITA BRNO', 1, 'Brno');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (360, 'CZ BRNO01', 66, 'VYSOKE UCENI TECHNICKE V BRNE', 1, 'BRNO STRED');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (361, 'CZ CESKE01', 66, 'JIHOCESKA UNIVERZITA V CESKYCH BUDEJOVICICH', 1, 'CESKE BUDEJOVICE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (362, 'CZ PRAHA07', 66, 'UNIVERZITA KARLOVA', 1, 'PRAHA 1');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (363, 'RO BUCURES11', 188, 'UNIVERSITATEA POLITEHNICA DIN BUCURESTI', 1, 'BUCHAREST');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (364, 'RO BUCURES13', 188, 'SCOALA NATIONALA DE STUDII POLITICE SI ADMINISTRATIVE', 1, 'BUCURESTI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (365, 'RO BUCURES07', 188, 'UNIVERSITATEA DE ARCHITECTURA SI URBANISM ION MINCU DIN BUCURESTI', 1, 'BUCURESTI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (366, 'RO BUCURES09', 188, 'UNIVERSITATEA DIN BUCURESTI', 1, 'BUCURESTI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (367, 'RO CLUJNAP01', 188, 'UNIVERSITATEA BABES BOLYAI', 1, 'CLUJ NAPOCA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (368, 'RO CRAIOVA01', 188, 'UNIVERSITATEA DIN CRAIOVA', 1, 'CRAIOVA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (369, 'RO IASI05', 188, 'UNIVERSITATEA TEHNICA GHEORGHE ASACHI DIN IASI', 1, 'IASI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (370, 'RO SIBIU01', 188, 'UNIVERSITATEA LUCIAN BLAGA DIN SIBIU', 1, 'SIBIU');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (371, 'RO TIMISOA01', 188, 'UNIVERSITATEA DE VEST DIN TIMISOARA', 1, 'TIMISOARA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (372, 'RO TIMISOA04', 188, 'UNIVERSITATEA POLITEHNICA TIMISOARA', 1, 'TIMISOARA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (373, 'S  BORAS01', 221, 'HOEGSKOLAN I BORAS', 1, 'BORAS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (374, 'S  FALUN01', 221, 'HOGSKOLAN DALARNA', 1, 'FALUN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (375, 'S  GOTEBOR01', 221, 'GOETEBORGS UNIVERSITET', 1, 'GOETEBORG');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (376, 'S  LINKOPI01', 221, 'LINKOPINGS UNIVERSITET', 1, 'LINKOPING');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (377, 'S  OREBRO01', 221, 'OREBRO UNIVERSITY', 1, 'OREBRO');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (378, 'S  SKOVDE01', 221, 'HOGSKOLAN I SKOVDE', 1, 'SKOVDE');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (379, 'S  STOCKHO01', 221, 'STOCKHOLMS UNIVERSITET', 1, 'STOCKHOLM');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (380, 'S  TROLLHA01', 221, 'HOGSKOLAN VAST', 1, 'TROLLHATTAN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (381, 'S  UMEA01', 221, 'UMEA UNIVERSITET', 1, 'UMEA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (382, 'S  UPPSALA01', 221, 'UPPSALA UNIVERSITET', 1, 'UPPSALA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (383, 'S  VASTERA01', 221, 'MAELARDALENS HOEGSKOLA', 1, 'VASTERAS');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (384, 'TR IZMIR01', 234, 'DOKUZ EYLUL UNIVERSITESI', 1, 'ALSANCAK IZMIR');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (385, 'TR ANKARA15', 234, 'ANKARA YILDIRIM BEYAZIT UNIVERSITESI', 1, 'ANKARA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (386, 'TR ANKARA02', 234, 'GAZI UNIVERSITESI', 1, 'ANKARA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (387, 'TR ANKARA03', 234, 'HACETTEPE UNIVERSITESI', 1, 'CANKAYA ANKARA');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (388, 'TR DENIZLI01', 234, 'Pamukkale Universitesi', 1, 'DENIZLI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (389, 'TR ELAZIG01', 234, 'FIRAT UNIVERSITESI', 1, 'Elazig');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (390, 'TR ISTANBU43', 234, 'Istanbul 29 Mayis Universitesi', 1, 'Istanbul');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (391, 'TR ISTANBU19', 234, 'ISTANBUL KULTUR UNIVERSITY', 1, 'ISTANBUL');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (392, 'TR ISTANBU21', 234, 'YEDITEPE UNIVERSITY VAKIF', 1, 'Istanbul');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (393, 'TR IZMIR05', 234, 'YASAR UNIVERSITESI', 1, 'IZMIR');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (394, 'TR KAYSERI01', 234, 'ERCIYES UNIVERSITESI', 1, 'KAYSERI');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (395, 'TR ISTANBU04', 234, 'ISTANBUL TEKNIK UNIVERSITESI', 1, 'MASLAK ISTANBUL');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (396, 'TR ANKARA01', 234, 'ANKARA UNIVERSITESI', 1, 'TANDOGAN');
INSERT INTO erappsmus.universidades (id, codigo, pais, nombre, hace_erasmus, ciudad) VALUES (404, 'UC3M', 215, 'Universidad Carlos III', 1, 'Madrid');
